/* tslint:disable */
/* eslint-disable */
/**
 * Agent Manager API
 * AIエージェントによるスクラム開発プロセスを自律的に実行するタスク管理システムのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Agent,
} from '../models/index';
import {
    AgentFromJSON,
    AgentToJSON,
} from '../models/index';

export interface AgentsAgentIdGetRequest {
    agentId: string;
}

/**
 * 
 */
export class AgentsApi extends runtime.BaseAPI {

    /**
     * AIエージェント詳細取得
     */
    async agentsAgentIdGetRaw(requestParameters: AgentsAgentIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Agent>> {
        if (requestParameters['agentId'] == null) {
            throw new runtime.RequiredError(
                'agentId',
                'Required parameter "agentId" was null or undefined when calling agentsAgentIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/agents/{agentId}`.replace(`{${"agentId"}}`, encodeURIComponent(String(requestParameters['agentId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentFromJSON(jsonValue));
    }

    /**
     * AIエージェント詳細取得
     */
    async agentsAgentIdGet(requestParameters: AgentsAgentIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Agent> {
        const response = await this.agentsAgentIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * AIエージェント一覧取得
     */
    async agentsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Agent>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/agents`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AgentFromJSON));
    }

    /**
     * AIエージェント一覧取得
     */
    async agentsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Agent>> {
        const response = await this.agentsGetRaw(initOverrides);
        return await response.value();
    }

}
