/* tslint:disable */
/* eslint-disable */
/**
 * Agent Manager API
 * AIエージェントによるスクラム開発プロセスを自律的に実行するタスク管理システムのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateReviewRequest,
  Review,
  UpdateReviewRequest,
} from '../models/index';
import {
    CreateReviewRequestFromJSON,
    CreateReviewRequestToJSON,
    ReviewFromJSON,
    ReviewToJSON,
    UpdateReviewRequestFromJSON,
    UpdateReviewRequestToJSON,
} from '../models/index';

export interface ReviewsPostRequest {
    createReviewRequest: CreateReviewRequest;
}

export interface ReviewsReviewIdGetRequest {
    reviewId: string;
}

export interface ReviewsReviewIdPutRequest {
    reviewId: string;
    updateReviewRequest: UpdateReviewRequest;
}

/**
 * 
 */
export class ReviewsApi extends runtime.BaseAPI {

    /**
     * スプリントレビュー作成
     */
    async reviewsPostRaw(requestParameters: ReviewsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Review>> {
        if (requestParameters['createReviewRequest'] == null) {
            throw new runtime.RequiredError(
                'createReviewRequest',
                'Required parameter "createReviewRequest" was null or undefined when calling reviewsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/reviews`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateReviewRequestToJSON(requestParameters['createReviewRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReviewFromJSON(jsonValue));
    }

    /**
     * スプリントレビュー作成
     */
    async reviewsPost(requestParameters: ReviewsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Review> {
        const response = await this.reviewsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * レビュー詳細取得
     */
    async reviewsReviewIdGetRaw(requestParameters: ReviewsReviewIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Review>> {
        if (requestParameters['reviewId'] == null) {
            throw new runtime.RequiredError(
                'reviewId',
                'Required parameter "reviewId" was null or undefined when calling reviewsReviewIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/reviews/{reviewId}`.replace(`{${"reviewId"}}`, encodeURIComponent(String(requestParameters['reviewId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReviewFromJSON(jsonValue));
    }

    /**
     * レビュー詳細取得
     */
    async reviewsReviewIdGet(requestParameters: ReviewsReviewIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Review> {
        const response = await this.reviewsReviewIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * レビュー更新
     */
    async reviewsReviewIdPutRaw(requestParameters: ReviewsReviewIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Review>> {
        if (requestParameters['reviewId'] == null) {
            throw new runtime.RequiredError(
                'reviewId',
                'Required parameter "reviewId" was null or undefined when calling reviewsReviewIdPut().'
            );
        }

        if (requestParameters['updateReviewRequest'] == null) {
            throw new runtime.RequiredError(
                'updateReviewRequest',
                'Required parameter "updateReviewRequest" was null or undefined when calling reviewsReviewIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/reviews/{reviewId}`.replace(`{${"reviewId"}}`, encodeURIComponent(String(requestParameters['reviewId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateReviewRequestToJSON(requestParameters['updateReviewRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReviewFromJSON(jsonValue));
    }

    /**
     * レビュー更新
     */
    async reviewsReviewIdPut(requestParameters: ReviewsReviewIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Review> {
        const response = await this.reviewsReviewIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
