/* tslint:disable */
/* eslint-disable */
/**
 * Agent Manager API
 * AIエージェントによるスクラム開発プロセスを自律的に実行するタスク管理システムのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BurndownChart,
  CreateSprintRequest,
  Sprint,
  Task,
  UpdateSprintRequest,
} from '../models/index';
import {
    BurndownChartFromJSON,
    BurndownChartToJSON,
    CreateSprintRequestFromJSON,
    CreateSprintRequestToJSON,
    SprintFromJSON,
    SprintToJSON,
    TaskFromJSON,
    TaskToJSON,
    UpdateSprintRequestFromJSON,
    UpdateSprintRequestToJSON,
} from '../models/index';

export interface SprintsGetRequest {
    projectId: string;
}

export interface SprintsPostRequest {
    createSprintRequest: CreateSprintRequest;
}

export interface SprintsSprintIdBurndownGetRequest {
    sprintId: string;
}

export interface SprintsSprintIdGetRequest {
    sprintId: string;
}

export interface SprintsSprintIdPlanPostRequest {
    sprintId: string;
}

export interface SprintsSprintIdPutRequest {
    sprintId: string;
    updateSprintRequest: UpdateSprintRequest;
}

export interface SprintsSprintIdTasksGetRequest {
    sprintId: string;
}

/**
 * 
 */
export class SprintsApi extends runtime.BaseAPI {

    /**
     * スプリント一覧取得
     */
    async sprintsGetRaw(requestParameters: SprintsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Sprint>>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling sprintsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['projectId'] != null) {
            queryParameters['projectId'] = requestParameters['projectId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/sprints`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SprintFromJSON));
    }

    /**
     * スプリント一覧取得
     */
    async sprintsGet(requestParameters: SprintsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Sprint>> {
        const response = await this.sprintsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * スプリント作成
     */
    async sprintsPostRaw(requestParameters: SprintsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sprint>> {
        if (requestParameters['createSprintRequest'] == null) {
            throw new runtime.RequiredError(
                'createSprintRequest',
                'Required parameter "createSprintRequest" was null or undefined when calling sprintsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/sprints`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSprintRequestToJSON(requestParameters['createSprintRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SprintFromJSON(jsonValue));
    }

    /**
     * スプリント作成
     */
    async sprintsPost(requestParameters: SprintsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sprint> {
        const response = await this.sprintsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * バーンダウンチャートデータ取得
     */
    async sprintsSprintIdBurndownGetRaw(requestParameters: SprintsSprintIdBurndownGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BurndownChart>> {
        if (requestParameters['sprintId'] == null) {
            throw new runtime.RequiredError(
                'sprintId',
                'Required parameter "sprintId" was null or undefined when calling sprintsSprintIdBurndownGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/sprints/{sprintId}/burndown`.replace(`{${"sprintId"}}`, encodeURIComponent(String(requestParameters['sprintId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BurndownChartFromJSON(jsonValue));
    }

    /**
     * バーンダウンチャートデータ取得
     */
    async sprintsSprintIdBurndownGet(requestParameters: SprintsSprintIdBurndownGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BurndownChart> {
        const response = await this.sprintsSprintIdBurndownGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * スプリント詳細取得
     */
    async sprintsSprintIdGetRaw(requestParameters: SprintsSprintIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sprint>> {
        if (requestParameters['sprintId'] == null) {
            throw new runtime.RequiredError(
                'sprintId',
                'Required parameter "sprintId" was null or undefined when calling sprintsSprintIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/sprints/{sprintId}`.replace(`{${"sprintId"}}`, encodeURIComponent(String(requestParameters['sprintId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SprintFromJSON(jsonValue));
    }

    /**
     * スプリント詳細取得
     */
    async sprintsSprintIdGet(requestParameters: SprintsSprintIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sprint> {
        const response = await this.sprintsSprintIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * スクラムマスターAIがスプリントプランを作成
     * スプリントプラン（AI実行）
     */
    async sprintsSprintIdPlanPostRaw(requestParameters: SprintsSprintIdPlanPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sprint>> {
        if (requestParameters['sprintId'] == null) {
            throw new runtime.RequiredError(
                'sprintId',
                'Required parameter "sprintId" was null or undefined when calling sprintsSprintIdPlanPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/sprints/{sprintId}/plan`.replace(`{${"sprintId"}}`, encodeURIComponent(String(requestParameters['sprintId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SprintFromJSON(jsonValue));
    }

    /**
     * スクラムマスターAIがスプリントプランを作成
     * スプリントプラン（AI実行）
     */
    async sprintsSprintIdPlanPost(requestParameters: SprintsSprintIdPlanPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sprint> {
        const response = await this.sprintsSprintIdPlanPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * スプリント更新
     */
    async sprintsSprintIdPutRaw(requestParameters: SprintsSprintIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Sprint>> {
        if (requestParameters['sprintId'] == null) {
            throw new runtime.RequiredError(
                'sprintId',
                'Required parameter "sprintId" was null or undefined when calling sprintsSprintIdPut().'
            );
        }

        if (requestParameters['updateSprintRequest'] == null) {
            throw new runtime.RequiredError(
                'updateSprintRequest',
                'Required parameter "updateSprintRequest" was null or undefined when calling sprintsSprintIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/sprints/{sprintId}`.replace(`{${"sprintId"}}`, encodeURIComponent(String(requestParameters['sprintId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateSprintRequestToJSON(requestParameters['updateSprintRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SprintFromJSON(jsonValue));
    }

    /**
     * スプリント更新
     */
    async sprintsSprintIdPut(requestParameters: SprintsSprintIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Sprint> {
        const response = await this.sprintsSprintIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * スプリントバックログ取得
     */
    async sprintsSprintIdTasksGetRaw(requestParameters: SprintsSprintIdTasksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Task>>> {
        if (requestParameters['sprintId'] == null) {
            throw new runtime.RequiredError(
                'sprintId',
                'Required parameter "sprintId" was null or undefined when calling sprintsSprintIdTasksGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/sprints/{sprintId}/tasks`.replace(`{${"sprintId"}}`, encodeURIComponent(String(requestParameters['sprintId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TaskFromJSON));
    }

    /**
     * スプリントバックログ取得
     */
    async sprintsSprintIdTasksGet(requestParameters: SprintsSprintIdTasksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Task>> {
        const response = await this.sprintsSprintIdTasksGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
