/* tslint:disable */
/* eslint-disable */
/**
 * Agent Manager API
 * AIエージェントによるスクラム開発プロセスを自律的に実行するタスク管理システムのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateTaskRequest,
  Task,
  TaskExecutionResult,
  UpdateTaskRequest,
} from '../models/index';
import {
    CreateTaskRequestFromJSON,
    CreateTaskRequestToJSON,
    TaskFromJSON,
    TaskToJSON,
    TaskExecutionResultFromJSON,
    TaskExecutionResultToJSON,
    UpdateTaskRequestFromJSON,
    UpdateTaskRequestToJSON,
} from '../models/index';

export interface ProjectsProjectIdBacklogGetRequest {
    projectId: string;
}

export interface TasksPostRequest {
    createTaskRequest: CreateTaskRequest;
}

export interface TasksTaskIdDeleteRequest {
    taskId: string;
}

export interface TasksTaskIdExecutePostRequest {
    taskId: string;
}

export interface TasksTaskIdGetRequest {
    taskId: string;
}

export interface TasksTaskIdPutRequest {
    taskId: string;
    updateTaskRequest: UpdateTaskRequest;
}

export interface TasksTaskIdSplitPostRequest {
    taskId: string;
}

/**
 * 
 */
export class TasksApi extends runtime.BaseAPI {

    /**
     * プロダクトバックログ取得
     */
    async projectsProjectIdBacklogGetRaw(requestParameters: ProjectsProjectIdBacklogGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Task>>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectsProjectIdBacklogGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/projects/{projectId}/backlog`.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TaskFromJSON));
    }

    /**
     * プロダクトバックログ取得
     */
    async projectsProjectIdBacklogGet(requestParameters: ProjectsProjectIdBacklogGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Task>> {
        const response = await this.projectsProjectIdBacklogGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * タスク作成
     */
    async tasksPostRaw(requestParameters: TasksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Task>> {
        if (requestParameters['createTaskRequest'] == null) {
            throw new runtime.RequiredError(
                'createTaskRequest',
                'Required parameter "createTaskRequest" was null or undefined when calling tasksPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/tasks`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTaskRequestToJSON(requestParameters['createTaskRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskFromJSON(jsonValue));
    }

    /**
     * タスク作成
     */
    async tasksPost(requestParameters: TasksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Task> {
        const response = await this.tasksPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * タスク削除
     */
    async tasksTaskIdDeleteRaw(requestParameters: TasksTaskIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling tasksTaskIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/tasks/{taskId}`.replace(`{${"taskId"}}`, encodeURIComponent(String(requestParameters['taskId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * タスク削除
     */
    async tasksTaskIdDelete(requestParameters: TasksTaskIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.tasksTaskIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * AIがタスクを自律的に実行
     * タスク実行（AI実行）
     */
    async tasksTaskIdExecutePostRaw(requestParameters: TasksTaskIdExecutePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaskExecutionResult>> {
        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling tasksTaskIdExecutePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/tasks/{taskId}/execute`.replace(`{${"taskId"}}`, encodeURIComponent(String(requestParameters['taskId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskExecutionResultFromJSON(jsonValue));
    }

    /**
     * AIがタスクを自律的に実行
     * タスク実行（AI実行）
     */
    async tasksTaskIdExecutePost(requestParameters: TasksTaskIdExecutePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaskExecutionResult> {
        const response = await this.tasksTaskIdExecutePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * タスク詳細取得
     */
    async tasksTaskIdGetRaw(requestParameters: TasksTaskIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Task>> {
        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling tasksTaskIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/tasks/{taskId}`.replace(`{${"taskId"}}`, encodeURIComponent(String(requestParameters['taskId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskFromJSON(jsonValue));
    }

    /**
     * タスク詳細取得
     */
    async tasksTaskIdGet(requestParameters: TasksTaskIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Task> {
        const response = await this.tasksTaskIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * タスク更新
     */
    async tasksTaskIdPutRaw(requestParameters: TasksTaskIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Task>> {
        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling tasksTaskIdPut().'
            );
        }

        if (requestParameters['updateTaskRequest'] == null) {
            throw new runtime.RequiredError(
                'updateTaskRequest',
                'Required parameter "updateTaskRequest" was null or undefined when calling tasksTaskIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/tasks/{taskId}`.replace(`{${"taskId"}}`, encodeURIComponent(String(requestParameters['taskId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTaskRequestToJSON(requestParameters['updateTaskRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaskFromJSON(jsonValue));
    }

    /**
     * タスク更新
     */
    async tasksTaskIdPut(requestParameters: TasksTaskIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Task> {
        const response = await this.tasksTaskIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 複雑なタスクをAIが自動的に小さなタスクに分割
     * タスク分割（AI実行）
     */
    async tasksTaskIdSplitPostRaw(requestParameters: TasksTaskIdSplitPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Task>>> {
        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling tasksTaskIdSplitPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/tasks/{taskId}/split`.replace(`{${"taskId"}}`, encodeURIComponent(String(requestParameters['taskId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TaskFromJSON));
    }

    /**
     * 複雑なタスクをAIが自動的に小さなタスクに分割
     * タスク分割（AI実行）
     */
    async tasksTaskIdSplitPost(requestParameters: TasksTaskIdSplitPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Task>> {
        const response = await this.tasksTaskIdSplitPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
