/* tslint:disable */
/* eslint-disable */
/**
 * Agent Manager API
 * AIエージェントによるスクラム開発プロセスを自律的に実行するタスク管理システムのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Agent
 */
export interface Agent {
    /**
     * 
     * @type {string}
     * @memberof Agent
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Agent
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Agent
     */
    role?: AgentRoleEnum;
    /**
     * AI提供元（例：GitHub Copilot）
     * @type {string}
     * @memberof Agent
     */
    aiProvider?: string;
    /**
     * 
     * @type {string}
     * @memberof Agent
     */
    status?: AgentStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof Agent
     */
    createdAt?: Date;
}


/**
 * @export
 */
export const AgentRoleEnum = {
    ProductOwner: 'PRODUCT_OWNER',
    ScrumMaster: 'SCRUM_MASTER',
    Developer: 'DEVELOPER',
    Reviewer: 'REVIEWER',
    Qa: 'QA'
} as const;
export type AgentRoleEnum = typeof AgentRoleEnum[keyof typeof AgentRoleEnum];

/**
 * @export
 */
export const AgentStatusEnum = {
    Active: 'ACTIVE',
    Inactive: 'INACTIVE'
} as const;
export type AgentStatusEnum = typeof AgentStatusEnum[keyof typeof AgentStatusEnum];


/**
 * Check if a given object implements the Agent interface.
 */
export function instanceOfAgent(value: object): value is Agent {
    return true;
}

export function AgentFromJSON(json: any): Agent {
    return AgentFromJSONTyped(json, false);
}

export function AgentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Agent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'role': json['role'] == null ? undefined : json['role'],
        'aiProvider': json['aiProvider'] == null ? undefined : json['aiProvider'],
        'status': json['status'] == null ? undefined : json['status'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function AgentToJSON(json: any): Agent {
    return AgentToJSONTyped(json, false);
}

export function AgentToJSONTyped(value?: Agent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'role': value['role'],
        'aiProvider': value['aiProvider'],
        'status': value['status'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

