/* tslint:disable */
/* eslint-disable */
/**
 * Agent Manager API
 * AIエージェントによるスクラム開発プロセスを自律的に実行するタスク管理システムのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BurndownChartDataPointsInner
 */
export interface BurndownChartDataPointsInner {
    /**
     * 
     * @type {Date}
     * @memberof BurndownChartDataPointsInner
     */
    date?: Date;
    /**
     * 
     * @type {number}
     * @memberof BurndownChartDataPointsInner
     */
    remainingStoryPoints?: number;
    /**
     * 
     * @type {number}
     * @memberof BurndownChartDataPointsInner
     */
    idealStoryPoints?: number;
}

/**
 * Check if a given object implements the BurndownChartDataPointsInner interface.
 */
export function instanceOfBurndownChartDataPointsInner(value: object): value is BurndownChartDataPointsInner {
    return true;
}

export function BurndownChartDataPointsInnerFromJSON(json: any): BurndownChartDataPointsInner {
    return BurndownChartDataPointsInnerFromJSONTyped(json, false);
}

export function BurndownChartDataPointsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): BurndownChartDataPointsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'remainingStoryPoints': json['remainingStoryPoints'] == null ? undefined : json['remainingStoryPoints'],
        'idealStoryPoints': json['idealStoryPoints'] == null ? undefined : json['idealStoryPoints'],
    };
}

export function BurndownChartDataPointsInnerToJSON(json: any): BurndownChartDataPointsInner {
    return BurndownChartDataPointsInnerToJSONTyped(json, false);
}

export function BurndownChartDataPointsInnerToJSONTyped(value?: BurndownChartDataPointsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'] == null ? undefined : ((value['date']).toISOString().substring(0,10)),
        'remainingStoryPoints': value['remainingStoryPoints'],
        'idealStoryPoints': value['idealStoryPoints'],
    };
}

