/* tslint:disable */
/* eslint-disable */
/**
 * Agent Manager API
 * AIエージェントによるスクラム開発プロセスを自律的に実行するタスク管理システムのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BurndownChartDataPointsInner } from './BurndownChartDataPointsInner';
import {
    BurndownChartDataPointsInnerFromJSON,
    BurndownChartDataPointsInnerFromJSONTyped,
    BurndownChartDataPointsInnerToJSON,
    BurndownChartDataPointsInnerToJSONTyped,
} from './BurndownChartDataPointsInner';

/**
 * 
 * @export
 * @interface BurndownChart
 */
export interface BurndownChart {
    /**
     * 
     * @type {string}
     * @memberof BurndownChart
     */
    sprintId?: string;
    /**
     * 
     * @type {Array<BurndownChartDataPointsInner>}
     * @memberof BurndownChart
     */
    dataPoints?: Array<BurndownChartDataPointsInner>;
}

/**
 * Check if a given object implements the BurndownChart interface.
 */
export function instanceOfBurndownChart(value: object): value is BurndownChart {
    return true;
}

export function BurndownChartFromJSON(json: any): BurndownChart {
    return BurndownChartFromJSONTyped(json, false);
}

export function BurndownChartFromJSONTyped(json: any, ignoreDiscriminator: boolean): BurndownChart {
    if (json == null) {
        return json;
    }
    return {
        
        'sprintId': json['sprintId'] == null ? undefined : json['sprintId'],
        'dataPoints': json['dataPoints'] == null ? undefined : ((json['dataPoints'] as Array<any>).map(BurndownChartDataPointsInnerFromJSON)),
    };
}

export function BurndownChartToJSON(json: any): BurndownChart {
    return BurndownChartToJSONTyped(json, false);
}

export function BurndownChartToJSONTyped(value?: BurndownChart | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sprintId': value['sprintId'],
        'dataPoints': value['dataPoints'] == null ? undefined : ((value['dataPoints'] as Array<any>).map(BurndownChartDataPointsInnerToJSON)),
    };
}

