/* tslint:disable */
/* eslint-disable */
/**
 * Agent Manager API
 * AIエージェントによるスクラム開発プロセスを自律的に実行するタスク管理システムのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSprintRequest
 */
export interface CreateSprintRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateSprintRequest
     */
    projectId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSprintRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSprintRequest
     */
    goal: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateSprintRequest
     */
    startDate?: Date;
}

/**
 * Check if a given object implements the CreateSprintRequest interface.
 */
export function instanceOfCreateSprintRequest(value: object): value is CreateSprintRequest {
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('goal' in value) || value['goal'] === undefined) return false;
    return true;
}

export function CreateSprintRequestFromJSON(json: any): CreateSprintRequest {
    return CreateSprintRequestFromJSONTyped(json, false);
}

export function CreateSprintRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSprintRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['projectId'],
        'name': json['name'],
        'goal': json['goal'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
    };
}

export function CreateSprintRequestToJSON(json: any): CreateSprintRequest {
    return CreateSprintRequestToJSONTyped(json, false);
}

export function CreateSprintRequestToJSONTyped(value?: CreateSprintRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'projectId': value['projectId'],
        'name': value['name'],
        'goal': value['goal'],
        'startDate': value['startDate'] == null ? undefined : ((value['startDate']).toISOString()),
    };
}

