/* tslint:disable */
/* eslint-disable */
/**
 * Agent Manager API
 * AIエージェントによるスクラム開発プロセスを自律的に実行するタスク管理システムのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTaskRequest
 */
export interface CreateTaskRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateTaskRequest
     */
    projectId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskRequest
     */
    parentTaskId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskRequest
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskRequest
     */
    priority?: CreateTaskRequestPriorityEnum;
    /**
     * 
     * @type {number}
     * @memberof CreateTaskRequest
     */
    storyPoint?: number;
}


/**
 * @export
 */
export const CreateTaskRequestPriorityEnum = {
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Critical: 'CRITICAL'
} as const;
export type CreateTaskRequestPriorityEnum = typeof CreateTaskRequestPriorityEnum[keyof typeof CreateTaskRequestPriorityEnum];


/**
 * Check if a given object implements the CreateTaskRequest interface.
 */
export function instanceOfCreateTaskRequest(value: object): value is CreateTaskRequest {
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function CreateTaskRequestFromJSON(json: any): CreateTaskRequest {
    return CreateTaskRequestFromJSONTyped(json, false);
}

export function CreateTaskRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTaskRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['projectId'],
        'parentTaskId': json['parentTaskId'] == null ? undefined : json['parentTaskId'],
        'title': json['title'],
        'description': json['description'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'storyPoint': json['storyPoint'] == null ? undefined : json['storyPoint'],
    };
}

export function CreateTaskRequestToJSON(json: any): CreateTaskRequest {
    return CreateTaskRequestToJSONTyped(json, false);
}

export function CreateTaskRequestToJSONTyped(value?: CreateTaskRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'projectId': value['projectId'],
        'parentTaskId': value['parentTaskId'],
        'title': value['title'],
        'description': value['description'],
        'priority': value['priority'],
        'storyPoint': value['storyPoint'],
    };
}

