/* tslint:disable */
/* eslint-disable */
/**
 * Agent Manager API
 * AIエージェントによるスクラム開発プロセスを自律的に実行するタスク管理システムのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateReviewRequest
 */
export interface CreateReviewRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateReviewRequest
     */
    sprintId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateReviewRequest
     */
    reviewerId: string;
    /**
     * 
     * @type {number}
     * @memberof CreateReviewRequest
     */
    rating: number;
    /**
     * 
     * @type {string}
     * @memberof CreateReviewRequest
     */
    comment?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateReviewRequest
     */
    approved: boolean;
}

/**
 * Check if a given object implements the CreateReviewRequest interface.
 */
export function instanceOfCreateReviewRequest(value: object): value is CreateReviewRequest {
    if (!('sprintId' in value) || value['sprintId'] === undefined) return false;
    if (!('reviewerId' in value) || value['reviewerId'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('approved' in value) || value['approved'] === undefined) return false;
    return true;
}

export function CreateReviewRequestFromJSON(json: any): CreateReviewRequest {
    return CreateReviewRequestFromJSONTyped(json, false);
}

export function CreateReviewRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateReviewRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'sprintId': json['sprintId'],
        'reviewerId': json['reviewerId'],
        'rating': json['rating'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'approved': json['approved'],
    };
}

export function CreateReviewRequestToJSON(json: any): CreateReviewRequest {
    return CreateReviewRequestToJSONTyped(json, false);
}

export function CreateReviewRequestToJSONTyped(value?: CreateReviewRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sprintId': value['sprintId'],
        'reviewerId': value['reviewerId'],
        'rating': value['rating'],
        'comment': value['comment'],
        'approved': value['approved'],
    };
}

