/* tslint:disable */
/* eslint-disable */
/**
 * Agent Manager API
 * AIエージェントによるスクラム開発プロセスを自律的に実行するタスク管理システムのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Review
 */
export interface Review {
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    sprintId?: string;
    /**
     * レビュー実施者（人間）のID
     * @type {string}
     * @memberof Review
     */
    reviewerId?: string;
    /**
     * 成果物の評価（1-5）
     * @type {number}
     * @memberof Review
     */
    rating?: number;
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    comment?: string;
    /**
     * 承認フラグ
     * @type {boolean}
     * @memberof Review
     */
    approved?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Review
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Review
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the Review interface.
 */
export function instanceOfReview(value: object): value is Review {
    return true;
}

export function ReviewFromJSON(json: any): Review {
    return ReviewFromJSONTyped(json, false);
}

export function ReviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): Review {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'sprintId': json['sprintId'] == null ? undefined : json['sprintId'],
        'reviewerId': json['reviewerId'] == null ? undefined : json['reviewerId'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'approved': json['approved'] == null ? undefined : json['approved'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function ReviewToJSON(json: any): Review {
    return ReviewToJSONTyped(json, false);
}

export function ReviewToJSONTyped(value?: Review | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'sprintId': value['sprintId'],
        'reviewerId': value['reviewerId'],
        'rating': value['rating'],
        'comment': value['comment'],
        'approved': value['approved'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

