/* tslint:disable */
/* eslint-disable */
/**
 * Agent Manager API
 * AIエージェントによるスクラム開発プロセスを自律的に実行するタスク管理システムのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Sprint
 */
export interface Sprint {
    /**
     * 
     * @type {string}
     * @memberof Sprint
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Sprint
     */
    projectId?: string;
    /**
     * 
     * @type {string}
     * @memberof Sprint
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Sprint
     */
    goal?: string;
    /**
     * 
     * @type {string}
     * @memberof Sprint
     */
    status?: SprintStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof Sprint
     */
    startDate?: Date | null;
    /**
     * AIが自動設定（レビュータイミング）
     * @type {Date}
     * @memberof Sprint
     */
    endDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Sprint
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Sprint
     */
    updatedAt?: Date;
}


/**
 * @export
 */
export const SprintStatusEnum = {
    Planned: 'PLANNED',
    Active: 'ACTIVE',
    Completed: 'COMPLETED'
} as const;
export type SprintStatusEnum = typeof SprintStatusEnum[keyof typeof SprintStatusEnum];


/**
 * Check if a given object implements the Sprint interface.
 */
export function instanceOfSprint(value: object): value is Sprint {
    return true;
}

export function SprintFromJSON(json: any): Sprint {
    return SprintFromJSONTyped(json, false);
}

export function SprintFromJSONTyped(json: any, ignoreDiscriminator: boolean): Sprint {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'name': json['name'] == null ? undefined : json['name'],
        'goal': json['goal'] == null ? undefined : json['goal'],
        'status': json['status'] == null ? undefined : json['status'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function SprintToJSON(json: any): Sprint {
    return SprintToJSONTyped(json, false);
}

export function SprintToJSONTyped(value?: Sprint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'projectId': value['projectId'],
        'name': value['name'],
        'goal': value['goal'],
        'status': value['status'],
        'startDate': value['startDate'] == null ? undefined : ((value['startDate'] as any).toISOString()),
        'endDate': value['endDate'] == null ? undefined : ((value['endDate'] as any).toISOString()),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

