/* tslint:disable */
/* eslint-disable */
/**
 * Agent Manager API
 * AIエージェントによるスクラム開発プロセスを自律的に実行するタスク管理システムのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Task
 */
export interface Task {
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    projectId?: string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    sprintId?: string | null;
    /**
     * 親タスクID（タスク分割時）
     * @type {string}
     * @memberof Task
     */
    parentTaskId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    priority?: TaskPriorityEnum;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    status?: TaskStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    assignedAgentId?: string | null;
    /**
     * ストーリーポイント（進捗可視化用）
     * @type {number}
     * @memberof Task
     */
    storyPoint?: number | null;
    /**
     * 成果物のパス
     * @type {string}
     * @memberof Task
     */
    artifactPath?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Task
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Task
     */
    updatedAt?: Date;
}


/**
 * @export
 */
export const TaskPriorityEnum = {
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Critical: 'CRITICAL'
} as const;
export type TaskPriorityEnum = typeof TaskPriorityEnum[keyof typeof TaskPriorityEnum];

/**
 * @export
 */
export const TaskStatusEnum = {
    Backlog: 'BACKLOG',
    SprintBacklog: 'SPRINT_BACKLOG',
    InProgress: 'IN_PROGRESS',
    Review: 'REVIEW',
    Done: 'DONE'
} as const;
export type TaskStatusEnum = typeof TaskStatusEnum[keyof typeof TaskStatusEnum];


/**
 * Check if a given object implements the Task interface.
 */
export function instanceOfTask(value: object): value is Task {
    return true;
}

export function TaskFromJSON(json: any): Task {
    return TaskFromJSONTyped(json, false);
}

export function TaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): Task {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'sprintId': json['sprintId'] == null ? undefined : json['sprintId'],
        'parentTaskId': json['parentTaskId'] == null ? undefined : json['parentTaskId'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'status': json['status'] == null ? undefined : json['status'],
        'assignedAgentId': json['assignedAgentId'] == null ? undefined : json['assignedAgentId'],
        'storyPoint': json['storyPoint'] == null ? undefined : json['storyPoint'],
        'artifactPath': json['artifactPath'] == null ? undefined : json['artifactPath'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function TaskToJSON(json: any): Task {
    return TaskToJSONTyped(json, false);
}

export function TaskToJSONTyped(value?: Task | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'projectId': value['projectId'],
        'sprintId': value['sprintId'],
        'parentTaskId': value['parentTaskId'],
        'title': value['title'],
        'description': value['description'],
        'priority': value['priority'],
        'status': value['status'],
        'assignedAgentId': value['assignedAgentId'],
        'storyPoint': value['storyPoint'],
        'artifactPath': value['artifactPath'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

