/* tslint:disable */
/* eslint-disable */
/**
 * Agent Manager API
 * AIエージェントによるスクラム開発プロセスを自律的に実行するタスク管理システムのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskExecutionResult
 */
export interface TaskExecutionResult {
    /**
     * 
     * @type {string}
     * @memberof TaskExecutionResult
     */
    taskId?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskExecutionResult
     */
    status?: TaskExecutionResultStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof TaskExecutionResult
     */
    artifactPath?: string | null;
    /**
     * Git commit hash
     * @type {string}
     * @memberof TaskExecutionResult
     */
    commitHash?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TaskExecutionResult
     */
    message?: string;
    /**
     * 
     * @type {Date}
     * @memberof TaskExecutionResult
     */
    executedAt?: Date;
}


/**
 * @export
 */
export const TaskExecutionResultStatusEnum = {
    Success: 'SUCCESS',
    Failed: 'FAILED',
    InProgress: 'IN_PROGRESS'
} as const;
export type TaskExecutionResultStatusEnum = typeof TaskExecutionResultStatusEnum[keyof typeof TaskExecutionResultStatusEnum];


/**
 * Check if a given object implements the TaskExecutionResult interface.
 */
export function instanceOfTaskExecutionResult(value: object): value is TaskExecutionResult {
    return true;
}

export function TaskExecutionResultFromJSON(json: any): TaskExecutionResult {
    return TaskExecutionResultFromJSONTyped(json, false);
}

export function TaskExecutionResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskExecutionResult {
    if (json == null) {
        return json;
    }
    return {
        
        'taskId': json['taskId'] == null ? undefined : json['taskId'],
        'status': json['status'] == null ? undefined : json['status'],
        'artifactPath': json['artifactPath'] == null ? undefined : json['artifactPath'],
        'commitHash': json['commitHash'] == null ? undefined : json['commitHash'],
        'message': json['message'] == null ? undefined : json['message'],
        'executedAt': json['executedAt'] == null ? undefined : (new Date(json['executedAt'])),
    };
}

export function TaskExecutionResultToJSON(json: any): TaskExecutionResult {
    return TaskExecutionResultToJSONTyped(json, false);
}

export function TaskExecutionResultToJSONTyped(value?: TaskExecutionResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'taskId': value['taskId'],
        'status': value['status'],
        'artifactPath': value['artifactPath'],
        'commitHash': value['commitHash'],
        'message': value['message'],
        'executedAt': value['executedAt'] == null ? undefined : ((value['executedAt']).toISOString()),
    };
}

