/* tslint:disable */
/* eslint-disable */
/**
 * Agent Manager API
 * AIエージェントによるスクラム開発プロセスを自律的に実行するタスク管理システムのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProjectRequest
 */
export interface UpdateProjectRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectRequest
     */
    status?: UpdateProjectRequestStatusEnum;
}


/**
 * @export
 */
export const UpdateProjectRequestStatusEnum = {
    Active: 'ACTIVE',
    Archived: 'ARCHIVED'
} as const;
export type UpdateProjectRequestStatusEnum = typeof UpdateProjectRequestStatusEnum[keyof typeof UpdateProjectRequestStatusEnum];


/**
 * Check if a given object implements the UpdateProjectRequest interface.
 */
export function instanceOfUpdateProjectRequest(value: object): value is UpdateProjectRequest {
    return true;
}

export function UpdateProjectRequestFromJSON(json: any): UpdateProjectRequest {
    return UpdateProjectRequestFromJSONTyped(json, false);
}

export function UpdateProjectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProjectRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function UpdateProjectRequestToJSON(json: any): UpdateProjectRequest {
    return UpdateProjectRequestToJSONTyped(json, false);
}

export function UpdateProjectRequestToJSONTyped(value?: UpdateProjectRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'status': value['status'],
    };
}

