/* tslint:disable */
/* eslint-disable */
/**
 * Agent Manager API
 * AIエージェントによるスクラム開発プロセスを自律的に実行するタスク管理システムのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTaskRequest
 */
export interface UpdateTaskRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskRequest
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskRequest
     */
    priority?: UpdateTaskRequestPriorityEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskRequest
     */
    status?: UpdateTaskRequestStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskRequest
     */
    assignedAgentId?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateTaskRequest
     */
    storyPoint?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskRequest
     */
    sprintId?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskRequest
     */
    artifactPath?: string;
}


/**
 * @export
 */
export const UpdateTaskRequestPriorityEnum = {
    Low: 'LOW',
    Medium: 'MEDIUM',
    High: 'HIGH',
    Critical: 'CRITICAL'
} as const;
export type UpdateTaskRequestPriorityEnum = typeof UpdateTaskRequestPriorityEnum[keyof typeof UpdateTaskRequestPriorityEnum];

/**
 * @export
 */
export const UpdateTaskRequestStatusEnum = {
    Backlog: 'BACKLOG',
    SprintBacklog: 'SPRINT_BACKLOG',
    InProgress: 'IN_PROGRESS',
    Review: 'REVIEW',
    Done: 'DONE'
} as const;
export type UpdateTaskRequestStatusEnum = typeof UpdateTaskRequestStatusEnum[keyof typeof UpdateTaskRequestStatusEnum];


/**
 * Check if a given object implements the UpdateTaskRequest interface.
 */
export function instanceOfUpdateTaskRequest(value: object): value is UpdateTaskRequest {
    return true;
}

export function UpdateTaskRequestFromJSON(json: any): UpdateTaskRequest {
    return UpdateTaskRequestFromJSONTyped(json, false);
}

export function UpdateTaskRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTaskRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'status': json['status'] == null ? undefined : json['status'],
        'assignedAgentId': json['assignedAgentId'] == null ? undefined : json['assignedAgentId'],
        'storyPoint': json['storyPoint'] == null ? undefined : json['storyPoint'],
        'sprintId': json['sprintId'] == null ? undefined : json['sprintId'],
        'artifactPath': json['artifactPath'] == null ? undefined : json['artifactPath'],
    };
}

export function UpdateTaskRequestToJSON(json: any): UpdateTaskRequest {
    return UpdateTaskRequestToJSONTyped(json, false);
}

export function UpdateTaskRequestToJSONTyped(value?: UpdateTaskRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'priority': value['priority'],
        'status': value['status'],
        'assignedAgentId': value['assignedAgentId'],
        'storyPoint': value['storyPoint'],
        'sprintId': value['sprintId'],
        'artifactPath': value['artifactPath'],
    };
}

