/* tslint:disable */
/* eslint-disable */
/**
 * Agent Manager API
 * AIエージェントによるスクラム開発プロセスを自律的に実行するタスク管理システムのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSprintRequest
 */
export interface UpdateSprintRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateSprintRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateSprintRequest
     */
    goal?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateSprintRequest
     */
    status?: UpdateSprintRequestStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof UpdateSprintRequest
     */
    endDate?: Date;
}


/**
 * @export
 */
export const UpdateSprintRequestStatusEnum = {
    Planned: 'PLANNED',
    Active: 'ACTIVE',
    Completed: 'COMPLETED'
} as const;
export type UpdateSprintRequestStatusEnum = typeof UpdateSprintRequestStatusEnum[keyof typeof UpdateSprintRequestStatusEnum];


/**
 * Check if a given object implements the UpdateSprintRequest interface.
 */
export function instanceOfUpdateSprintRequest(value: object): value is UpdateSprintRequest {
    return true;
}

export function UpdateSprintRequestFromJSON(json: any): UpdateSprintRequest {
    return UpdateSprintRequestFromJSONTyped(json, false);
}

export function UpdateSprintRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSprintRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'goal': json['goal'] == null ? undefined : json['goal'],
        'status': json['status'] == null ? undefined : json['status'],
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
    };
}

export function UpdateSprintRequestToJSON(json: any): UpdateSprintRequest {
    return UpdateSprintRequestToJSONTyped(json, false);
}

export function UpdateSprintRequestToJSONTyped(value?: UpdateSprintRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'goal': value['goal'],
        'status': value['status'],
        'endDate': value['endDate'] == null ? undefined : ((value['endDate']).toISOString()),
    };
}

