/* tslint:disable */
/* eslint-disable */
/**
 * Agent Manager API
 * AIエージェントによるスクラム開発プロセスを自律的に実行するタスク管理システムのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateReviewRequest
 */
export interface UpdateReviewRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdateReviewRequest
     */
    rating?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateReviewRequest
     */
    comment?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateReviewRequest
     */
    approved?: boolean;
}

/**
 * Check if a given object implements the UpdateReviewRequest interface.
 */
export function instanceOfUpdateReviewRequest(value: object): value is UpdateReviewRequest {
    return true;
}

export function UpdateReviewRequestFromJSON(json: any): UpdateReviewRequest {
    return UpdateReviewRequestFromJSONTyped(json, false);
}

export function UpdateReviewRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateReviewRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'rating': json['rating'] == null ? undefined : json['rating'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'approved': json['approved'] == null ? undefined : json['approved'],
    };
}

export function UpdateReviewRequestToJSON(json: any): UpdateReviewRequest {
    return UpdateReviewRequestToJSONTyped(json, false);
}

export function UpdateReviewRequestToJSONTyped(value?: UpdateReviewRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rating': value['rating'],
        'comment': value['comment'],
        'approved': value['approved'],
    };
}

